services:
  chats-service:
    container_name: mzhn-chats-service
    build:
      context: .
    env_file:
      - .env
    environment:
      WAIT_HOSTS: pgc:5432
      PG_HOST: pgc
      PG_PORT: 5432
      ENV: prod
    depends_on:
      - pgc
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"

  pgc:
    image: postgres:14.13-alpine3.20
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    volumes:
      - chats_pg_data:/var/lib/postgresql/data
    ports:
      - 5444:5432

volumes:
  chats_pg_data:
    name: mzhn-chats-pg
